### ISSUE TITLE
"buy now" button

### ISSUE THREAD

**Issue by trinib** [SebaLG/amazon-python-bot#1]
hi..nice script but i dont think it would make sense if it has no 'buy now' button like controller's PAGE for EXAMPLE
![image](https://user-images.githubusercontent.com/18756975/99890954-0f850300-2c3b-11eb-8565-cf9a1c9d1066.png)

**Comment by trinib** [comment]
THIS WORKS FOR ME WITH NEW XPATHS

from selenium import webdriver
from time import sleep

class PS5Bot():
    def __init__(self):
        self.driver = webdriver.Chrome()

    def login(self):
        self.driver.get('https://www.amazon.com')
        sleep(50)

    def checkAndBuyPS5(self):
        self.driver.get('THE LINK TO THE SHIT YOU WANT TO BUY')
        sleep(1)   
        try:
            buyNow = self.driver.find_element_by_xpath('//*[@id="add-to-cart-button"]')
            buyNow.click()
            sleep(2)
            buyNow2 = self.driver.find_element_by_xpath('//*[@id="hlb-ptc-btn"]')
            buyNow2.click()
            sleep(2)
            buyNow3 = self.driver.find_element_by_xpath('/html/body/div[5]/div/div[2]/form/div/div/div/div[2]/div/div[1]/div/div[1]/div/span/span/input')  
            buyNow3.click()
            sleep(1)
            self.driver.close()
        except Exception as e:
            print(e)
            sleep(3)
            self.checkAndBuyPS5()
bot = PS5Bot()
bot.login()
bot.checkAndBuyPS5()

**Comment by trinib** [comment]
THIS WORKS FOR ME WITH NEW XPATHS 

```
from selenium import webdriver
from time import sleep

class PS5Bot():
    def __init__(self):
        self.driver = webdriver.Chrome()

    def login(self):
        self.driver.get('https://www.amazon.com')
        sleep(50)

    def checkAndBuyPS5(self):
        self.driver.get('THE SHIT YOU WANT TO BUY')
        sleep(1)   
        try:
            buyNow = self.driver.find_element_by_xpath('//*[@id="add-to-cart-button"]')
            buyNow.click()
            sleep(2)
            buyNow2 = self.driver.find_element_by_xpath('//*[@id="hlb-ptc-btn"]')
            buyNow2.click()
            sleep(2)
            buyNow3 = self.driver.find_element_by_xpath('/html/body/div[5]/div/div[2]/form/div/div/div/div[2]/div/div[1]/div/div[1]/div/span/span/input')  
            buyNow3.click()
            sleep(1)
            self.driver.close()
        except Exception as e:
            print(e)
            sleep(1.5)
            self.checkAndBuyPS5()
bot = PS5Bot()
bot.login()
bot.checkAndBuyPS5()
```

**Comment by SebaLopez94** [comment]
Thanks @trinib, I already fix the problem with the XPATH with your suggestion.

**Comment by trinib** [comment]
> Thanks @trinib, I already fix the problem with the XPATH with your suggestion. 

cool... I see you copied over the whole thing I edited .. please note that  I changed the sleep from 3 to 1.5 in last "buy" condition / function or whatever you call it.. still a nood 😅.. just in cuase some1 internet or browser is slow and refreshing takes longer.. I guess they will figure out that by themselves
